@baseUrl = http://95.217.205.57:13500/school-api/
# @baseUrl = http://localhost:13502/

###

GET {{baseUrl}}Program/getCampusProgram?campusID=101


###
GET {{baseUrl}}University/getCountry

###

GET {{baseUrl}}University/getProvince?CountryID=1

###
GET {{baseUrl}}University/getCity?ProvinceID=1


###
GET {{baseUrl}}University/getUniversityCampusProgram?educationTypeID=3&programID=43&cityID=1

###
GET {{baseUrl}}Program/getEducationType

###
GET  https://api.nuget.org/v3/index.json
